### ISSUE TITLE
Hi~ I have some problem

### ISSUE THREAD

**Issue by robin30518** [tarekmuallim/Multicam-Intel-Realsense-D400#1]
Hello, thanks for provide this code, I am using vs2015 and two d415, it can successfully compile, but when I start running, I saw two d415 Activated, but nothing happened, it stop on the pcl's visualizer, and appear a circle Rotated in the center. Did you use the connect wire to sync two d415 ??

thanks for reading this question and providing this code.

**Comment by tarekmuallim** [comment]
Hi
Sorry for late reply. 
I do not know why I didn't get notification from github for your issue. Maybe you should tag me on your post. 
I am using two realsense cameras. Each one connected separately through USB cable to the pc. The two cameras form a cluster.

**Comment by tarekmuallim** [comment]
![dsc_2432](https://user-images.githubusercontent.com/38329913/48822536-7af71a00-ed6e-11e8-93e9-ef07ea1c66d1.JPG)

**Comment by tarekmuallim** [comment]
@robin30518
