### ISSUE TITLE
[question] Cannot load PCL related dll file in running time

### ISSUE THREAD

**Issue by cindy0628** [tarekmuallim/Multicam-Intel-Realsense-D400#2]
Hi,
I want to implement 2 d435 devices with your code,
but it showed error "Loaded 'C:\Program Files\PCL 1.8.1\bin\pcl_common_release.dll'. Module was built without symbols.", and it didn't create point cloud in running time.  please see the picture as below:
![123](https://user-images.githubusercontent.com/26700548/90497823-1d2d7700-e17a-11ea-8cd4-8b4f529c2725.png)

Could you kindly advise how to solve this problem, thank you.

**Comment by tarekmuallim** [comment]
Hi @cindy0628 
it looks a problem with PCL.
did you install PCL correctly at your computer?

**Comment by cindy0628** [comment]
Yes, I did. I use **PCL-1.8.1-AllInOne-msvc2017-win64.exe** to install.
Is it possible cause by the setting of VisualStudio?

**Comment by tarekmuallim** [comment]
you have to set your project to release mode.
